repository: DHP-stottepakke/pages

github_repo: https://github.com/DHP-stottepakke/pages

github_branch: main

site_url: https://plan.research-data.no

github_edit_url: "{{ site_url }}/edit/{{ github_branch }}/"

title: "plan.research-data.no"
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ''
# this appears on the top navigation bar next to the home button

description: "Data Management Planning Support Package for Norwegian Higher Education Libraries"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@4.1.0

dsw_deep_link_prefix: https://norway.fair-wizard.com/wizard/

theme_variables:
  git_host: GitHub
  back_to_top: true
  theme_color: ba0c2f
  fonts:
    - https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap
  github_buttons:
    position: top
    edit_me: true
    open_issue: true
    history: true
  topnav:
    theme: dark
    brand_logo: assets/img/main_logo.svg
  toc:
    min_headings: 1
    headings: 'h2'

permalink: pretty

exclude:
  - README.md
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    permalink: /:basename
    layout: "page"
    sidebar: main
    topnav: topnav
-
  scope:
    path: "pages/contribute"
    type: "contribute"
  values:
    permalink: /contribute
    layout: "page"
    sidebar: about
    topnav: topnav

plugins:
  - elixir-toolkit-theme-plugins
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
