name: Link Checker

on:
  repository_dispatch:
  workflow_dispatch:    
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4


      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0


      - name: Install dependencies
        run: |
            bundle install
      - name: Build with Jekyll
          # Outputs to the './_site' directory by default
        run: |
            bundle exec jekyll build
        env:
            PAGES_REPO_NWO: ${{ github.repository }}
            JEKYLL_BUILD_BRANCH: ${{ github.ref_name }}
            JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
            # Check all markdown, html and reStructuredText files in repo (default)
            args: _site/ --fallback-extensions .html
            # Don't fail action on broken links
            fail: false
            
      - name: Add page URL
        run: |
            DEPLOY_URL="https://plan.research-data.no/pages/" && \
            sed -i "s|### Errors in _site\/|${DEPLOY_URL}|g" ./lychee/out.md && \
            cat ./lychee/out.md
            
      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
          issue-number: 12
